

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nesro35
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.22.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Nesro35@postgres:5432/cinema_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" 
      HASURA_GRAPHQL_ENABLE_EVENT_TRIGGERS: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: mysecretkey
    depends_on:
      - postgres

  golang-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      HASURA_GRAPHQL_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_ADMIN_SECRET: mysecretkey
    ports:
      - "8081:8081"
    depends_on:
      - hasura

volumes:
  postgres_data:
